server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
        - id: greet-service
          uri: lb://greet-service
          predicates:
            - Path=/greet/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
